spring:

  datasource:
    url: jdbc:mysql://13.124.41.123:3306/Emergency_Link
    username: el
    password: el12!@
    driver-class-name: com.mysql.cj.jdbc.Driver


serviceKey: sk-proj-D7gKlckIY7aoxIpw6je8T3BlbkFJBJFFuwjNONQbiwmSL1a6