spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Emergency_Link
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


serviceKey: qfSddXLIM345%2BsZvxylN8VEt%2Bd87ZJyFy0h5Re%2BB%2BvgCVufIYNo90jdBjXwizSY5Oc7C8RlB8vkGfxLEItPwkQ%3D%3D