
name: EL-Frontend
on:
  push:
    branches: 
      - main
    paths:
      - 'el-front/**'
      - '.github/workflows/node.yml'
  pull_request:
    branches: 
      - main
    paths:
      - 'el-front/**'
      - '.github/workflows/node.yml'
jobs:
  build:
    runs-on : [el-front]

    strategy :
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      

      - name: Use Node.js '20.12.2' in el-front
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
          cache: 'npm'
          cache-dependency-path: ./el-front

      - name: Install dependencies
        run: npm install
        working-directory: el-front

      - name: Build project
        run: npm run build --if-present
        working-directory: el-front

      - name: Stop Nginx
        run: sudo service nginx stop

      - name: Start Nginx
        run: sudo service nginx start