
name: EL-Frontend
on:
  push:
    branches: 
      - main
    paths:
      - 'el-front/**'
      - '.github/workflows/node.yml'
  pull_request:
    branches: 
      - main
    paths:
      - 'el-front/**'
      - '.github/workflows/node.yml'

jobs:
  build:
    runs-on : [el-front]

    strategy :
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - run: |
          
          cd el-front

      - name: Use Node.js '20.12.2'
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
          cache: 'npm'
      - run: |
          npm install
          npm run build --if-present

      - name: Stop Nginx
        run: sudo service nginx stop
      - name: Start Nginx
        run: sudo service nginx start